version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: empower_db
      POSTGRES_USER: empower_user
      POSTGRES_PASSWORD: empower_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Backend Flask API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://empower_user:empower_password@db:5432/empower_db
      - SECRET_KEY=dev-secret-key-change-in-production
      - JWT_SECRET_KEY=jwt-secret-key-change-in-production
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped
    command: >
      sh -c "
        python -c 'from app import create_app, db; app = create_app(); app.app_context().push(); db.create_all(); print(\"Database tables created!\")'
        && python seed_data.py
        && python run.py
      "

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
